/**
 * Build viewer vendor bundles.
 *
 * Reads third-party UMD bundles (vis-network / marked / dompurify) and emits
 * TypeScript modules that export each source as a string. The strings are
 * inlined into the SPA HTML at render time, giving the viewer full offline
 * capability without any CDN dependency.
 *
 * Run automatically before `tsc` (see package.json `build` script).
 *
 * @module scripts/build-vendor.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");
const require = createRequire(import.meta.url);

/**
 * @typedef {Object} VendorSpec
 * @property {string} id            - 文件 basename(不含 -source.ts)
 * @property {string} exportName    - 导出常量名
 * @property {string} modulePath    - require.resolve 用的相对路径
 * @property {string} packageName   - package.json 名(用于版本探测)
 * @property {string} description   - 注释描述
 */
/** @type {readonly VendorSpec[]} */
const VENDOR_SPECS = [
  {
    id: "vis-network-source",
    exportName: "VIS_NETWORK_SOURCE",
    modulePath: "vis-network/standalone/umd/vis-network.min.js",
    packageName: "vis-network",
    description: "vis-network standalone UMD bundle (graph view)",
  },
  {
    id: "marked-source",
    exportName: "MARKED_SOURCE",
    modulePath: "marked/marked.min.js",
    packageName: "marked",
    description: "marked UMD bundle (markdown renderer)",
  },
  {
    id: "dompurify-source",
    exportName: "DOMPURIFY_SOURCE",
    modulePath: "dompurify/dist/purify.min.js",
    packageName: "dompurify",
    description: "DOMPurify UMD bundle (XSS sanitizer for rendered markdown)",
  },
];

function resolveVendorPath(spec) {
  try {
    return require.resolve(spec.modulePath);
  } catch {
    return null;
  }
}

function readVersion(packageName) {
  try {
    const pkg = JSON.parse(
      readFileSync(require.resolve(`${packageName}/package.json`), "utf8"),
    );
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
}

function escapeForTemplateLiteral(raw) {
  return raw
    .replaceAll("\\", "\\\\")
    .replaceAll("`", "\\`")
    .replaceAll("${", "\\${")
    .replaceAll("</script>", "<\\/script>")
    .replaceAll("</style>", "<\\/style>");
}

const outDir = resolve(pkgRoot, "src/vendor");
mkdirSync(outDir, { recursive: true });

let wroteCount = 0;
let missingCount = 0;

for (const spec of VENDOR_SPECS) {
  const vendorPath = resolveVendorPath(spec);
  if (!vendorPath) {
    console.warn(
      `[build-vendor] ${spec.packageName} not installed; skipping ${spec.id}`,
    );
    missingCount += 1;
    continue;
  }

  const version = readVersion(spec.packageName);
  const rawSource = readFileSync(vendorPath, "utf8");
  const escaped = escapeForTemplateLiteral(rawSource);
  const outFile = resolve(outDir, `${spec.id}.ts`);
  const tsContent = `/* eslint-disable */
/**
 * Auto-generated by scripts/build-vendor.mjs.
 *
 * Source: ${spec.packageName}@${version} - ${spec.description}
 * (~${Math.round(rawSource.length / 1024)}KB minified)
 *
 * Inlined into the viewer SPA HTML so the viewer works offline without any
 * CDN dependency. Do NOT edit by hand — re-run \`pnpm build\` to refresh.
 */

export const ${spec.exportName} = \`${escaped}\`
`;

  writeFileSync(outFile, tsContent);
  console.warn(
    `[build-vendor] wrote ${outFile} (${Math.round(tsContent.length / 1024)}KB)`,
  );
  wroteCount += 1;
}

if (wroteCount === 0) {
  console.warn(
    "[build-vendor] no vendor bundles were written (all dependencies missing)",
  );
  process.exit(0);
}
